name: Template Cleanup Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Template Cleanup Action
        uses: thynclabs/template-transformer-and-cleanup@1.0.2
        with:
          search_keyword: "chatgpt-register-latest/hexo-template-butterfly"
          replace_keyword: ${{ github.repository }}
          github_url: ${{ github.server_url }}
          workflow_token: ${{ secrets.WORKFLOW_TOKEN }}
          repository: ${{ github.repository }}
          branch: ${{ github.ref }}
